D1
MikhailKuz/afina pull request #2
Opened 2019-10-10 17:59 UTC by MikhailKuz

2019-10-11 20:25 UTC, MikhailKuz commented on src/storage/SimpleLRU.cpp
> +       _current_size -= _lru_head->key.size() + _lru_head->value.size();
Replaced with _lru_tail

2019-10-11 20:54 UTC, MikhailKuz commented on src/storage/SimpleLRU.cpp
> +           _lru_tail->prev->next.reset();
Replaced with  _lru_tail = _lru_tail->prev;
                        _lru_tail->next.reset();

2019-10-11 20:56 UTC, MikhailKuz commented on src/storage/SimpleLRU.cpp
> +    _lru_head = std::move(temp);
Replaced with:
_lru_head->prev = temp.get();
_lru_head.swap(temp->next);
_lru_head.swap(temp);
_lru_head->prev = nullptr;

2019-10-11 20:58 UTC, MikhailKuz commented on src/storage/SimpleLRU.cpp
> +    }
Added else:
} else {
        _lru_tail = _lru_tail->prev;
}

2019-10-15 15:11 UTC, xphoenix requested changes
Убери все лишние файлы, это невозможно смотреть

2019-10-15 21:12 UTC, closed without merging